---

- name: ensure apt is up to date
  apt: upgrade=dist update_cache=yes

- name: install language pack
  apt: pkg={{ item }} state=present
  with_items: common_languages

- name: install custom packages
  apt: pkg={{ item }} state=present
  with_items: custom_packages
